# Generated by Django 4.2 on 2023-05-05 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catagory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='coupen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('discount_price', models.PositiveBigIntegerField()),
                ('expairy_date', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Medicine_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('medicine_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcate', to='admn.medicine_type')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=500)),
                ('is_available', models.BooleanField(blank=True, default=False, null=True)),
                ('image', models.ImageField(null=True, upload_to='media')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('catagory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admn.catagory')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admn.company')),
                ('medicine_type', models.ForeignKey(blank=True, limit_choices_to={'medicine_type': None}, null=True, on_delete=django.db.models.deletion.CASCADE, to='admn.medicine_type')),
            ],
        ),
        migrations.CreateModel(
            name='varient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(blank=True, choices=[('10ml', '10ml'), ('20ml', '20ml'), ('30ml', '30ml'), ('50ml', '50ml'), ('60ml', '60ml'), ('100ml', '100ml'), ('150ml', '150ml'), ('200ml', '200ml'), ('250ml', '250ml'), ('500ml', '500ml'), ('750ml', '750ml'), ('1000ml', '100ml'), ('500gm', '500gm'), ('650gm', '650gm'), ('1100gm', '1100gm'), ('1600gm', '1600gm')], max_length=100, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('stock', models.PositiveBigIntegerField(blank=True, null=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item', to='admn.product')),
            ],
        ),
    ]
