# Generated by Django 4.2 on 2023-05-05 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=100)),
                ('image', models.ImageField(upload_to='doc')),
                ('email_vr', models.CharField(max_length=1000, null=True)),
                ('is_varified', models.BooleanField(default=False)),
                ('address', models.TextField(max_length=200, null=True)),
                ('residence', models.TextField(max_length=200, null=True)),
                ('contact_number', models.PositiveIntegerField(null=True)),
                ('badge_id', models.CharField(max_length=50, null=True)),
                ('is_available', models.BooleanField(default=False)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='docter.department')),
            ],
        ),
    ]
