# Generated by Django 4.2 on 2023-05-11 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docter', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorprofile',
            name='email_vr',
        ),
        migrations.RemoveField(
            model_name='doctorprofile',
            name='is_varified',
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='email_verify',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='is_verify',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='contact_number',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
