# Generated by Django 4.2 on 2023-05-16 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docter', '0004_alter_doctorprofile_contact_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofile',
            name='contact_number',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
