# Generated by Django 4.2 on 2023-05-22 17:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docter', '0006_doctorprofile_consult_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofile',
            name='consult_end',
            field=models.TimeField(default=datetime.time(20, 0)),
        ),
    ]
