# Generated by Django 4.2 on 2023-05-06 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_refund_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='discount_restriction',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
