# Generated by Django 4.2 on 2023-05-06 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_order_discount_restriction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='discount_restriction',
        ),
    ]
