# Generated by Django 4.2 on 2023-05-09 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_order_cancel_date_order_delivery_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'pending'), ('shiped', 'shiped'), ('deliverd', 'deliverd'), ('cancel', 'cancel'), ('revoke', 'revoke')], default='pending', max_length=10, null=True),
        ),
    ]
