# Generated by Django 4.2 on 2023-05-10 00:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admn', '0001_initial'),
        ('home', '0011_alter_refund_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='Varient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admn.varient'),
        ),
    ]
