# Generated by Django 4.2 on 2023-05-10 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='email_verify',
            field=models.BooleanField(default=False),
        ),
    ]
