# Generated by Django 4.2 on 2023-05-11 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_patientprofile_email_verify'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientprofile',
            name='mobile_number',
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='contact_number',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
