# Generated by Django 4.2 on 2023-05-11 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0005_remove_patientprofile_mobile_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientprofile',
            name='contact_number',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
