# Generated by Django 4.2 on 2023-05-16 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0006_alter_patientprofile_contact_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='amount',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
